[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
gas_reports=["InfiniteLottery"]

remappings= [
  "@chainlink/=node_modules/@chainlink/",
  "@eth-optimism/=node_modules/@eth-optimism/",
  "@openzeppelin/=node_modules/@openzeppelin/",
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "eth-gas-reporter/=node_modules/eth-gas-reporter/",
  "forge-std/=lib/forge-std/src/",
  "hardhat/=node_modules/hardhat/",
]

[rpc_endpoints]
bsc_testnet = "${TESTNET_RPC_URL}"
[etherscan]
bsc_testnet = { key = "${BSCSCAN_API}", url="https://api-testnet.bscscan.com/", chain=97}